In [1]:
import numpy as np

In [2]:
d = np.loadtxt("/Users/fxb/Desktop/拼车预测实验/SIMU_RESULT_2000.csv", delimiter=',')

In [6]:
alpha = (d[:, 1:] > 0).astype(int)

In [7]:
deg = np.sum(alpha, axis=1)

In [8]:
init_d = d[:, 1:]
w = np.zeros((init_d.shape[0], init_d.shape[1]))
for j in range(init_d.shape[0]):
    for l in range(init_d.shape[1]):
        w[j, l] = np.inner(alpha[:, j], alpha[:, l] / deg) / deg[l]

In [10]:
new_d = w ** 5 @ init_d

In [21]:
OD_cluster = -np.ones(init_d.shape[0])
cluster_num = 0
for i in range(init_d.shape[0]):
    if OD_cluster[i] == -1:
        OD_cluster[new_d[i, :] > 1e-6] = cluster_num
        cluster_num += 1

In [19]:
np.savetxt("/Users/fxb/Desktop/拼车预测实验/CLUSTER_2000.csv", OD_cluster.reshape((OD_cluster.shape[0], 1)), fmt="%d")

In [3]:
import pickle

In [9]:
# with open("/Users/fxb/Desktop/拼车预测实验/WEIGHT_BGRAPH", "wb") as outfile:
#     pickle.dump(w, outfile)
# with open("/Users/fxb/Desktop/拼车预测实验/INIT_D", "wb") as outfile:
#     pickle.dump(init_d, outfile)

In [4]:
with open("/Users/fxb/Desktop/拼车预测实验/WEIGHT_BGRAPH", "rb") as outfile:
    w = pickle.load(outfile)

EOFError: Ran out of input

In [25]:
new_d = new_d + new_d.T

K = 20
NODE_NUM = new_d.shape[0]
MAX_ITER = 100
node_cluster = np.random.randint(low=0, high=K, size=NODE_NUM)
medoids = np.random.choice(np.arange(0, NODE_NUM), K, False)
iter_time = 0
while iter_time < MAX_ITER:
    is_converge = True
    for i in range(NODE_NUM):
        single_distance = new_d[i, medoids]
        if node_cluster[i] != np.argmax(single_distance):
            node_cluster[i] = np.argmax(single_distance)
            is_converge = False
    # avg_radius = np.zeros(K)
    for k in range(K):
        distance_of_kth_cluster = new_d[node_cluster == k, :]
        distance_of_kth_cluster = distance_of_kth_cluster[:, node_cluster == k]
        # avg_radius[k] = np.mean(distance_of_kth_cluster)
        min_distance_node_idx = np.argmax(np.sum(distance_of_kth_cluster, axis=0))
        min_distance_node_idx = np.arange(NODE_NUM)[node_cluster == k][min_distance_node_idx]
        if medoids[k] != min_distance_node_idx:
            medoids[k] = min_distance_node_idx
            is_converge = False
    # print(avg_radius)
    if is_converge:
        break
    iter_time += 1

In [27]:
np.savetxt("/Users/fxb/Desktop/拼车预测实验/CLUSTER_2000.csv", node_cluster.reshape((node_cluster.shape[0], 1)), fmt="%d")

In [11]:
import csv
OD_NUM = 2000
OD_filepath = "/Users/fxb/Desktop/拼车预测实验/OD_2000.csv"
OD_pairs = np.zeros((OD_NUM, 6))
with open(OD_filepath, mode='r') as file:
    data = csv.reader(file)
    head = next(data)
    id_col = head.index("id")
    x1_col = head.index("originX")
    y1_col = head.index("originY")
    x2_col = head.index("destX")
    y2_col = head.index("destY")
    lam_col = head.index("lambda")
    j = 0
    for row in data:
        x1 = int(row[x1_col])
        x2 = int(row[x2_col])
        y1 = int(row[y1_col])
        y2 = int(row[y2_col])
        lam = float(row[lam_col])
        OD_pairs[j, :] = np.array([[j, x1, y1, x2, y2, lam]])
        j += 1
        if j >= OD_NUM:
            break

In [14]:
MAX_OD_NUM = 100
for n in range(MAX_OD_NUM):
    new_OD_pairs = OD_pairs[new_d[n, :] > 0, :]
    np.savetxt("/Users/fxb/Desktop/误差测试/OD_Cluster_" + str(n) + ".csv", new_OD_pairs, fmt=('%d', '%d', '%d', '%d', '%d', '%.2f'), delimiter=',', header="id, originX, originY, destX, destY, lambda", comments='')

In [21]:
index = -np.ones(MAX_OD_NUM)
for n in range(MAX_OD_NUM):
    index[n] = np.sum(new_d[n, :n] > 0)

In [22]:
predict_result = np.zeros((MAX_OD_NUM, 3))
for n in range(MAX_OD_NUM):
    with open("/Users/fxb/Desktop/误差测试/OD_Cluster_Result_" + str(n) + ".csv", mode='r') as file:
        data = csv.reader(file)
        head = next(data)
        pw_col = head.index("Pw")
        lw_col = head.index("Lw")
        ew_col = head.index("ew")
        j = 0
        for row in data:
            if j < index[n]:
                j += 1
                continue
            pw = float(row[pw_col])
            lw = float(row[lw_col])
            ew = float(row[ew_col])
            predict_result[n, 0] = pw
            predict_result[n, 1] = lw
            predict_result[n, 2] = ew
            break

In [15]:
OD_filepath = "/Users/fxb/Desktop/拼车预测实验/RESULT_2000.csv"
global_predict_result = np.zeros((MAX_OD_NUM, 3))
with open(OD_filepath, mode='r') as file:
    data = csv.reader(file)
    head = next(data)
    pw_col = head.index("Pw")
    lw_col = head.index("Lw")
    ew_col = head.index("ew")
    j = 0
    for row in data:
        pw = float(row[pw_col])
        lw = float(row[lw_col])
        ew = float(row[ew_col])
        global_predict_result[j, 0] = pw
        global_predict_result[j, 1] = lw
        global_predict_result[j, 2] = ew
        j += 1
        if j >= MAX_OD_NUM:
            break

In [23]:
rel_error = np.abs(global_predict_result - predict_result) / global_predict_result

In [46]:
np.arange(2000)[init_d[0, :] > 0]

array([   0,   24,  158,  372,  477,  571,  678,  848,  942, 1000, 1022,
       1024, 1034, 1372, 1477, 1643, 1892])

In [20]:
np.mean(rel_error, axis=0)

array([0.07106474, 0.5229238 , 0.53007409])

In [19]:
np.max(rel_error, axis=0)

array([0.31552397, 5.47097742, 5.03095817])

In [24]:
np.mean(rel_error, axis=0)

array([0.00127837, 0.00094977, 0.00319884])

In [25]:
np.max(rel_error, axis=0)

array([0.01082707, 0.00563832, 0.05705437])